substitutions:
  LOCATION: "mylocation"
############################################
  DEVICE_NAME: "Radar ${LOCATION}"
  INPUT_PIN: "33"
  TX_PIN: "21"
  RX_PIN: "25"

#############################################################################################################################
# Typical configuration:
# ======================
# delay_det_time=5
#
# ind_max=32
# ind_min=2
#
# th1 is motion threshold, don't report value lower than
# th1=800
# mov_sn=3
#
# th1 is occupancy threshold, don't report value lower than
# th2=410
# occ_sn=5
#
# th3=50000 (long-range, higher value means detection at shorter range)
#############################################################################################################################

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main

esphome:
  name: radar_${LOCATION}
  name_add_mac_suffix: false
  on_boot:    #LD1115H Initial Setting
    priority: -200
    then:
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th1st = "th1=" + str_sprintf("%.0f",id(th1_motion).state) +" \n";
            return std::vector<uint8_t>(th1st.begin(), th1st.end());
      - delay: 250ms
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th2st = "th2=" + str_sprintf("%.0f",id(th2_occupancy).state) +" \n";
            return std::vector<uint8_t>(th2st.begin(), th2st.end());
      - delay: 250ms
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th3st = "th3=" + str_sprintf("%.0f",id(th3_range).state) +" \n";
            return std::vector<uint8_t>(th3st.begin(), th3st.end());

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #Thanks for @ssieb components.
    components: [ serial ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configuration of M5 Atom Lite onboard RGB LED
light:
- platform: fastled_clockless
  name: "${DEVICE_NAME} FastLED Light"
  id: fastled
  icon: "mdi:led-outline"
  chipset: WS2812
  pin: 27 # Fixed value for M5stack Atom Lite
  num_leds: 1
  rgb_order: grb

ota:
  password: !secret ota_password

logger:
  level: DEBUG

binary_sensor:
- platform: gpio
  name: "${DEVICE_NAME} Occupancy"
  id: occupancy
  device_class: occupancy
  icon: "mdi:radar"
  pin:
    number: ${INPUT_PIN}
    mode:
      input: true
      pullup: false

uart:
  id: LD1115H_UART_BUS
  tx_pin: ${TX_PIN}
  rx_pin: ${RX_PIN}
  baud_rate: 115200
  setup_priority: 200 #Set Priority To Prevent Boot Loop or Fail

number:
- platform: template
  name: "${DEVICE_NAME} th1 motion"
  id: th1_motion
  icon: "mdi:cogs"
  optimistic: true
  restore_value: true
  initial_value: 120
  min_value: 10
  max_value: 65535
  step: 10
  mode: box
  set_action:
    then:
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th1st = "th1=" + str_sprintf("%.0f",x) +" \n";
            return std::vector<uint8_t>(th1st.begin(), th1st.end());
      - delay: 250ms
      - uart.write: "save\n"


- platform: template
  name: "${DEVICE_NAME} th2 occupancy"
  id: th2_occupancy
  icon: "mdi:cogs"
  optimistic: true
  restore_value: true    
  initial_value: 250
  min_value: 10
  max_value: 65535
  step: 10
  mode: box
  set_action:
    then:
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th2st = "th2=" + str_sprintf("%.0f",x) +" \n";
            return std::vector<uint8_t>(th2st.begin(), th2st.end());
      - delay: 250ms
      - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} th3 range"
  id:   th3_range
  icon: "mdi:cogs"
  min_value: 0
  max_value: 65535
  initial_value: 250
  optimistic: true
  step: 1
  restore_value: true
  mode: slider
  set_action:
    then:
      - uart.write:
          id: LD1115H_UART_BUS
          data: !lambda |-
            std::string th3st = "th3=" + str_sprintf("%.0f",x) +" \n";
            return std::vector<uint8_t>(th3st.begin(), th3st.end());
      - delay: 250ms
      - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} dtime"
  id:   delay_det_time
  icon: "mdi:timer-sand-empty"
  min_value: 1
  max_value: 60
  initial_value: 5
  optimistic: true
  step: 1
  restore_value: true
  mode: box
  set_action:
    - uart.write: !lambda
                    int cm = (int)x;
                    std::string cms = "dtime=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 250ms
    - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} mov_sn"
  id:   mov_sn
  min_value: 0
  max_value: 255
  initial_value: 3
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write: !lambda
                    int cm = (int)x;
                    std::string cms = "mov_sn=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 250ms
    - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} occ_sn"
  id: occ_sn
  min_value: 0
  max_value: 255
  initial_value: 5
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write: !lambda
                    int cm = (int)x;
                    std::string cms = "occ_sn=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 250ms
    - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} ind_min"
  id:   ind_min
  min_value: 0
  max_value: 32
  initial_value: 2
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write: !lambda
                    int cm = (int)x;
                    std::string cms = "ind_min=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 250ms
    - uart.write: "save\n"

- platform: template
  name: "${DEVICE_NAME} ind_max"
  id:   ind_max
  min_value: 0
  max_value: 32
  initial_value: 32
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write: !lambda
                    int cm = (int)x;
                    std::string cms = "ind_max=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 250ms
    - uart.write: "save\n"

text_sensor:
  - platform: template
    name: "${DEVICE_NAME} mov"
    id: mov
    icon: "mdi:format-text"
  - platform: template
    name: "${DEVICE_NAME} occ"
    id: occ
    icon: "mdi:format-text"
  - platform: serial
    uart_id: LD1115H_UART_BUS
    name: "${DEVICE_NAME} debug"
    id:    uart_text
    icon: "mdi:format-text"
    internal: true #If Don't Want to See UART Receive Data, Set To True
    on_value:
      lambda: |-
        if (id(uart_text).state.substr(0,3) == "occ") {
          id(occ).publish_state(id(uart_text).state.substr(5).c_str());
        }
        else if (id(uart_text).state.substr(0,3) == "mov") {
          id(mov).publish_state(id(uart_text).state.substr(5).c_str());
        }

bluetooth_proxy:
  active: true

esp32_ble_tracker:

